[package]
name = "ggrrss"
version = "0.1.0"
authors = ["ThinkChaos <ThinkChaos@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix = "0.8"
actix-http = "0.2"
actix-service = "0.4"
actix-web = "1.0"
env_logger = "0.6"
futures = "0.1"
serde = "1.0"
